### ISSUE TITLE
Project to-do list

### ISSUE THREAD

**Issue by jgbispo** [jgbispo/coinbase-blockchain#1]
- [ ] Setup Project
- [ ] Login with Metamask
- [ ] Add Header
- [ ] Add Portfolio Component
- [ ] Add Sidebar
- [ ] Add Connected Wallet Componen
- [ ] Finish Sidebar Style
- [ ] Build Side Promo Element
- [ ] Add Chart & Balance 
- [ ] Calculate Total Balance & Query Sanity Database
- [ ] Add Modal
