### ISSUE TITLE
ToDo List

### ISSUE THREAD

**Issue by jgbispo** [jgbispo/coinbase-blockchain#3]
- [ ] Setup Project
- [ ] Login with Metamask
- [ ] Add Header
- [ ] Add Portfolio Component
- [ ] Add Sidebar
- [ ] Add Connected Wallet Componen
- [ ] Finish Sidebar Style
- [ ] Build Side Promo Element
- [ ] Add Chart & Balance 
- [ ] Calculate Total Balance & Query Sanity Database
- [ ] Add Modal
- [ ] Modal Routing & Transfer Crypto
- [ ] Switch Tokens
- [ ] Other Pages in the Modal

**Comment by jgbispo** [comment]
27- 99795-6389
